apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-system

commonLabels:
  env: dev
  cloud: kind
  region: localhost # cloud provider region
  deployment: local

resources:
- namespace.yaml
- strimzi-cluster-operator-0.20.0.yaml
- cluster-role-bindings.yaml